### PR TITLE
turkish translation

### PR DESCRIPTION
**Pull request by Baturax**
added turkish translation

### CODE REVIEW

**Comment by Radiokot** [comment]
Hey, thanks a lot! Someone dropped a one-star review in Google Play complaining about missing Turkish language, I'm sure they'll change the rating once your translation is released 😄

**Review by Radiokot — CHANGES_REQUESTED** [review]
Could you please translate plurals as well?
https://github.com/Radiokot/photoprism-android-client/blob/main/app/src/main/res/values/plurals.xml
*If you are not familiar with the Android plurals structure, read [this explanation and check out the example](https://developer.android.com/guide/topics/resources/string-resource#Plurals)*

**Comment by Baturax** [comment]
i editted thanks for adding

**Review by Radiokot — APPROVED** [review]
Great. Thank you 🙌🏻

**Pull request merged**
