### PR TITLE
add: Chinese translations.

### PR DESCRIPTION
**Pull request by cgcel**
Translate most of strings into Chinese.

### CODE REVIEW

**Comment by Radiokot** [comment]
Is the translation unfinished?

**Comment by cgcel** [comment]
> Is the translation unfinished?

Yes... there are some features I haven't used, so I keep the original text😂

**Comment by Radiokot** [comment]
Please, finish the rest when you have time. I will not merge the PR for now – partially done translation will confuse other users.
Thanks.

**Review by Radiokot — CHANGES_REQUESTED** [review]
The translation needs to be finished

**Comment by cgcel** [comment]
> Please, finish the rest when you have time. I will not merge the PR for now – partially done translation will confuse other users.
> Thanks.

Okey, I will work on it.

**Review by Radiokot — APPROVED** [review]

**Comment by Radiokot** [comment]
Chen, thanks a lot.

**Pull request merged**
