### PR TITLE
Added french translation

### PR DESCRIPTION
**Pull request by vhaudiquet**
This commit adds a french translation to the app.

Thank you for your awesome work !

### CODE REVIEW

**Comment by Radiokot** [comment]
Good evening, Valentin, thank you for your submission!
Please, complete the translation, fix the problems and then notify me, so I could complete the review. I'd be happy to include your work into the app, but it is not yet ready. Here are some screenshots with problems:

<p>





</p>

**Review by Radiokot — CHANGES_REQUESTED** [review]
https://github.com/Radiokot/photoprism-android-client/pull/120#issuecomment-1904624885

**Comment by vhaudiquet** [comment]
Hi, I think I fixed all of my mistakes, sorry for that.
However, I don't know where the text 'Normal/Slow/...' from your last screenshot comes from.
It does not seem to be in the 'string' value file. Is it a system string that is wrong because of your test environment, or something I should find in another file ?

Thank you for your time

**Comment by Radiokot** [comment]
The speed and size enums are string arrays among other strings. Take a look at the default (English) strings:
https://github.com/Radiokot/photoprism-android-client/blob/2af8ece50cd6bfbc96c63a7bfc0a0935af0fdc4e/app/src/main/res/values/strings.xml#L151-L168

**Comment by vhaudiquet** [comment]
Interesting, the Android Studio string editor does not show them. I modified the file by hand, this should do it.
Thank you for your time !

**Review by Radiokot — APPROVED** [review]
Thank you for fixing the issues. Well done, Valentin! The translation will be added in the next release.

**Pull request merged**
